name: Deploy to Cloud Run via Workload Identity Federation

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/188263521940/locations/global/workloadIdentityPools/github-pool3/providers/github-provider'
          service_account: 'new-github-actions@saikiran9640.iam.gserviceaccount.com'

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: 'saikiran9640'

      - name: Configure Docker
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          docker build -t us-central1-docker.pkg.dev/saikiran9640/repo-artifact/hello-annalect:latest .
          docker push us-central1-docker.pkg.dev/saikiran9640/repo-artifact/hello-annalect:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy hello-annalect \
            --image us-central1-docker.pkg.dev/saikiran9640/repo-artifact/hello-annalect:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
